
all:
	g++ main1.cpp -o main1 -fopenmp
	g++ main2.cpp -o main2 -Ofast -fopenmp
	g++ main3.cpp -o main3 -Ofast -fopenmp
	g++ main4.cpp -o main4 -Ofast -fopenmp
	g++ main5.cpp -o main5 -Ofast -fopenmp
	g++ main6.cpp -o main6 -Ofast -fopenmp
	g++ main7.cpp -o main7 -Ofast -fopenmp
clean:
	rm main1 main2 main3 main4 main5 main6 main7
